### ISSUE TITLE
Add traffic tracking

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/starsimhub.github.io#4]

**Comment by JSchripsema-IDM** [comment]
I'll follow up with ForumOne about adding this to the analytics dashboard today. To add the analytics tracking code:

1. Paste this code as high in the <head> of the page as possible: 
 

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'[https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f)](https://www.googletagmanager.com/gtm.js?id=%27+i+dl;f.parentNode.insertBefore(j,f));
})(window,document,'script','dataLayer','GTM-NK4K647');</script>

 
2. Paste this code immediately after the opening <body> tag:
 

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NK4K647"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

Thank you!

**Comment by cliffckerr** [comment]
Done
